version: '3.8'
services:
  app1:
    build:
      context: .
      dockerfile: ./Dockerfile
    hostname: app1
    depends_on:
      - postgres
    environment:
        - SPRING_SERVER_PORT=8082
        - SPRING_DATASOURCE_USERNAME=pessoa
        - SPRING_DATASOURCE_PASSWORD=pessoa12345
        - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/pessoa_db
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '500MB'

  app2:
    build:
      context: .
      dockerfile: ./Dockerfile
    hostname: app2
    depends_on:
      - postgres
    environment:
      - SPRING_SERVER_PORT=8081
      - SPRING_DATASOURCE_USERNAME=pessoa
      - SPRING_DATASOURCE_PASSWORD=pessoa12345
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/pessoa_db
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '500MB'

  postgres:
    image: 'postgres:16.1'
    environment:
      - POSTGRES_PASSWORD=pessoa12345
      - POSTGRES_USER=pessoa
      - POSTGRES_DB=pessoa_db
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '1900GB'
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:rw
    network_mode: host
    depends_on:
      - app1
      - app2
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '100Mb'


  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    network_mode: host
    depends_on:
      - postgres
